### ISSUE TITLE
IDA Pro 9.2: "AttributeError: 'SyncForm_t' object has no attribute 'broker'" in SyncPlugin.py

### ISSUE THREAD

**Issue by loqstrz** [bootleg/ret-sync#134]
Ret-Sync is not working on IDA Pro 9.2 

I tested it on IDA Pro 9.1 and it works there. 

IDA Pro 9.2 did get an UI upgrade from QT5 to QT6 so not sure if that is what causes it.

Doesn't matter what I open, this error always appears in the logs. I can open the same databases in 9.1 and no problems.

**Comment by loqstrz** [comment]
Specifically: 

```
"../SyncPlugin.py", line 1080, in cb_change_state
      if self.broker:
AttributeError: 'SyncForm_t' object has no attribute in 'broker'
```

**Comment by saidelike** [comment]
In particular this fix: https://github.com/bootleg/ret-sync/commit/042730f032d5d446acab73441a709c60331d6cbe
